/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedLuckyDrawInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "drawWinner"
      | "getEncryptedWinnerIndex"
      | "getEncryptedWinnerName"
      | "getParticipantAccount"
      | "getParticipantsCount"
      | "getWinnerAccount"
      | "protocolId"
      | "registerParticipant"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ParticipantRegistered" | "WinnerDrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "drawWinner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedWinnerIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedWinnerName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipantAccount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipantsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWinnerAccount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerParticipant",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "drawWinner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedWinnerIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedWinnerName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipantAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipantsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWinnerAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerParticipant",
    data: BytesLike
  ): Result;
}

export namespace ParticipantRegisteredEvent {
  export type InputTuple = [index: BigNumberish, account: AddressLike];
  export type OutputTuple = [index: bigint, account: string];
  export interface OutputObject {
    index: bigint;
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerDrawnEvent {
  export type InputTuple = [index: BigNumberish, account: AddressLike];
  export type OutputTuple = [index: bigint, account: string];
  export interface OutputObject {
    index: bigint;
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedLuckyDraw extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedLuckyDraw;
  waitForDeployment(): Promise<this>;

  interface: EncryptedLuckyDrawInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  drawWinner: TypedContractMethod<[], [bigint], "nonpayable">;

  getEncryptedWinnerIndex: TypedContractMethod<[], [string], "view">;

  getEncryptedWinnerName: TypedContractMethod<[], [string], "view">;

  getParticipantAccount: TypedContractMethod<
    [index: BigNumberish],
    [string],
    "view"
  >;

  getParticipantsCount: TypedContractMethod<[], [bigint], "view">;

  getWinnerAccount: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  registerParticipant: TypedContractMethod<
    [encryptedNameHandle: BytesLike, inputProof: BytesLike],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "drawWinner"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getEncryptedWinnerIndex"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedWinnerName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getParticipantAccount"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getParticipantsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWinnerAccount"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerParticipant"
  ): TypedContractMethod<
    [encryptedNameHandle: BytesLike, inputProof: BytesLike],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "ParticipantRegistered"
  ): TypedContractEvent<
    ParticipantRegisteredEvent.InputTuple,
    ParticipantRegisteredEvent.OutputTuple,
    ParticipantRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "WinnerDrawn"
  ): TypedContractEvent<
    WinnerDrawnEvent.InputTuple,
    WinnerDrawnEvent.OutputTuple,
    WinnerDrawnEvent.OutputObject
  >;

  filters: {
    "ParticipantRegistered(uint256,address)": TypedContractEvent<
      ParticipantRegisteredEvent.InputTuple,
      ParticipantRegisteredEvent.OutputTuple,
      ParticipantRegisteredEvent.OutputObject
    >;
    ParticipantRegistered: TypedContractEvent<
      ParticipantRegisteredEvent.InputTuple,
      ParticipantRegisteredEvent.OutputTuple,
      ParticipantRegisteredEvent.OutputObject
    >;

    "WinnerDrawn(uint256,address)": TypedContractEvent<
      WinnerDrawnEvent.InputTuple,
      WinnerDrawnEvent.OutputTuple,
      WinnerDrawnEvent.OutputObject
    >;
    WinnerDrawn: TypedContractEvent<
      WinnerDrawnEvent.InputTuple,
      WinnerDrawnEvent.OutputTuple,
      WinnerDrawnEvent.OutputObject
    >;
  };
}
